//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftmatDesk.Models.DB_Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class softmatdeskEntities : DbContext
    {
        public softmatdeskEntities()
            : base("name=softmatdeskEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categorias> categorias { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<nivel_prioridad> nivel_prioridad { get; set; }
        public virtual DbSet<nivel_soporte> nivel_soporte { get; set; }
        public virtual DbSet<perfil> perfil { get; set; }
        public virtual DbSet<sedes> sedes { get; set; }
        public virtual DbSet<smusuarios> smusuarios { get; set; }
        public virtual DbSet<tickets> tickets { get; set; }
        public virtual DbSet<tipo_fallas> tipo_fallas { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
