//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftmatDesk.Models.DB_Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.tickets = new HashSet<tickets>();
        }
    
        public int idUsuario { get; set; }
        public int Cliente_idCliente { get; set; }
        public int idSede { get; set; }
        public int Perfil_idPerfil { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Correo { get; set; }
        public string Num_contacto { get; set; }
        public byte[] ImgPerfil { get; set; }
        public string NickName { get; set; }
        [Required]
        [StringLength(100)]
        public string Contraseña { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual perfil perfil { get; set; }
        public virtual sedes sedes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tickets> tickets { get; set; }
    }
}
